=== windowsjonathanmoore/Windows-2000/Samples/Web/author/databinding/MASTER_DETAIL/reportcard.dtd
<!ELEMENT REPORTCARD (STUDENT*)>
<!ELEMENT STUDENT (FNAME, LNAME, COURSE*)>
<!ELEMENT COURSE (MARK, SECTION, COURSENAME)>
<!ELEMENT FNAME (#PCDATA)>
<!ELEMENT LNAME (#PCDATA)>
<!ELEMENT MARK (#PCDATA)>
<!ELEMENT SECTION (#PCDATA)>
<!ELEMENT COURSENAME (#PCDATA)>

=== windowsjonathanmoore/Windows-2000/Samples/Web/author/databinding/MASTER_DETAIL/reportcard.xml
<!DOCTYPE REPORTCARD SYSTEM "reportcard.dtd">
<REPORTCARD><STUDENT><FNAME>Alex</FNAME><LNAME>Cannell</LNAME><COURSE><MARK>91</MARK><SECTION>01</SECTION><COURSENAME>MAT295S</COURSENAME></COURSE><COURSE><MARK>98</MARK><SECTION>02</SECTION><COURSENAME>AER201S</COURSENAME></COURSE><COURSE><MARK>55</MARK><SECTION>01</SECTION><COURSENAME>POL102Y</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>01</SECTION><COURSENAME>ECE253F</COURSENAME></COURSE><COURSE><MARK>97</MARK><SECTION>21</SECTION><COURSENAME>CSC205S</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Bob</FNAME><LNAME>Jennings</LNAME><COURSE><MARK>78</MARK><SECTION>01</SECTION><COURSENAME>CSC100</COURSENAME></COURSE><COURSE><MARK>66</MARK><SECTION>03</SECTION><COURSENAME>MAT123</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>12</SECTION><COURSENAME>AER103</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Susan</FNAME><LNAME>Montgomery</LNAME><COURSE><MARK>23</MARK><SECTION>21</SECTION><COURSENAME>ENG100</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Lee</FNAME><LNAME>Hansen</LNAME><COURSE><MARK>78</MARK><SECTION>05</SECTION><COURSENAME>PHY390</COURSENAME></COURSE><COURSE><MARK>44</MARK><SECTION>01</SECTION><COURSENAME>POL321</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>01</SECTION><COURSENAME>ENG333</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Johnny</FNAME><LNAME>Gamma</LNAME><COURSE><MARK>55</MARK><SECTION>04</SECTION><COURSENAME>PHY123</COURSENAME></COURSE><COURSE><MARK>90</MARK><SECTION>01</SECTION><COURSENAME>CSC100</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>04</SECTION><COURSENAME>MAT100</COURSENAME></COURSE><COURSE><MARK>56</MARK><SECTION>03</SECTION><COURSENAME>ECE102</COURSENAME></COURSE><COURSE><MARK>71</MARK><SECTION>07</SECTION><COURSENAME>CHE103</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Carter</FNAME><LNAME>Helmsley</LNAME><COURSE><MARK>56</MARK><SECTION>22</SECTION><COURSENAME>ENG100</COURSENAME></COURSE><COURSE><MARK>77</MARK><SECTION>02</SECTION><COURSENAME>POL201</COURSENAME></COURSE><COURSE><MARK>100</MARK><SECTION>02</SECTION><COURSENAME>MAT301</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>03</SECTION><COURSENAME>MAT302</COURSENAME></COURSE><COURSE><MARK>78</MARK><SECTION>05</SECTION><COURSENAME>PHY390</COURSENAME></COURSE><COURSE><MARK>44</MARK><SECTION>01</SECTION><COURSENAME>POL321</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>01</SECTION><COURSENAME>ENG333</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Ralph</FNAME><LNAME>Richardson</LNAME><COURSE><MARK>78</MARK><SECTION>01</SECTION><COURSENAME>CSC100</COURSENAME></COURSE><COURSE><MARK>66</MARK><SECTION>03</SECTION><COURSENAME>MAT123</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>12</SECTION><COURSENAME>AER103</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>John</FNAME><LNAME>Demopolous</LNAME><COURSE><MARK>77</MARK><SECTION>01</SECTION><COURSENAME>MAT400</COURSENAME></COURSE><COURSE><MARK>88</MARK><SECTION>02</SECTION><COURSENAME>ECE402</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>12</SECTION><COURSENAME>ENG100</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Lester</FNAME><LNAME>Davis</LNAME><COURSE><MARK>66</MARK><SECTION>04</SECTION><COURSENAME>CHE301</COURSENAME></COURSE><COURSE><MARK>89</MARK><SECTION>01</SECTION><COURSENAME>CHE308</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>12</SECTION><COURSENAME>CHE350</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Anita</FNAME><LNAME>Bowman</LNAME><COURSE><MARK>56</MARK><SECTION>01</SECTION><COURSENAME>ENG200</COURSENAME></COURSE><COURSE><MARK>66</MARK><SECTION>21</SECTION><COURSENAME>BIO150</COURSENAME></COURSE><COURSE><MARK>70</MARK><SECTION>12</SECTION><COURSENAME>CHE250</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Charles</FNAME><LNAME>Chesterfield</LNAME><COURSE><MARK>77</MARK><SECTION>01</SECTION><COURSENAME>MAT400</COURSENAME></COURSE><COURSE><MARK>88</MARK><SECTION>02</SECTION><COURSENAME>ECE402</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>12</SECTION><COURSENAME>ENG100</COURSENAME></COURSE><COURSE><MARK>78</MARK><SECTION>03</SECTION><COURSENAME>ECE405</COURSENAME></COURSE><COURSE><MARK>88</MARK><SECTION>01</SECTION><COURSENAME>ECE409</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Jessica</FNAME><LNAME>Lisbeth</LNAME><COURSE><MARK>99</MARK><SECTION>01</SECTION><COURSENAME>ENV200</COURSENAME></COURSE><COURSE><MARK>100</MARK><SECTION>21</SECTION><COURSENAME>BIO250</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>12</SECTION><COURSENAME>CHE289</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Kevin</FNAME><LNAME>Regis</LNAME><COURSE><MARK>89</MARK><SECTION>01</SECTION><COURSENAME>ECE250</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>03</SECTION><COURSENAME>ECE300</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>12</SECTION><COURSENAME>CSC208</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Jean</FNAME><LNAME>Marne</LNAME><COURSE><MARK>99</MARK><SECTION>01</SECTION><COURSENAME>POL400</COURSENAME></COURSE><COURSE><MARK>55</MARK><SECTION>02</SECTION><COURSENAME>POL540</COURSENAME></COURSE><COURSE><MARK>91</MARK><SECTION>01</SECTION><COURSENAME>ENG489</COURSENAME></COURSE></STUDENT><STUDENT><FNAME>Tom</FNAME><LNAME>Jones</LNAME><COURSE><MARK>66</MARK><SECTION>04</SECTION><COURSENAME>CHE301</COURSENAME></COURSE><COURSE><MARK>89</MARK><SECTION>01</SECTION><COURSENAME>CHE308</COURSENAME></COURSE><COURSE><MARK>99</MARK><SECTION>12</SECTION><COURSENAME>CHE350</COURSENAME></COURSE></STUDENT></REPORTCARD>
